Repository Durkastan/durkabot, pull requests merged in 2018-08, with the labels that each got.

#8 Add archive command
  src/extensions/archive/__init__.py
  src/extensions/archive/archive.py
  src/extensions/archive/archive_handler.py
  src/extensions/archive/archive_result.py
  tests/extensions/archive/test_archive_handler.py
  tests/res/archive.org_header_sample.json
  tests/res/archive.org_header_sample2.json
  tests/res/archive.org_header_sample3.json
Labels: enhancement

#10 Tests work on other machines
  tests/conftest.py
Labels: bug

#11 Updated python to 3.7 and refactored dataclasses to use decorator
  Dockerfile
  src/extensions/archive/archive_result.py
  src/extensions/booksearch/bookdata.py
Labels: enhancement

#16 Usability improvements
  src/main.py
  src/util.py
Labels: documentation, enhancement

#18 Shamela Booksearch
  src/extensions/archive/archive.py
  src/extensions/booksearch/booksearch.py
  src/extensions/booksearch/booksite.py
  src/extensions/booksearch/handlers/__init__.py
  src/extensions/booksearch/handlers/shamela_handler.py
  src/extensions/booksearch/handlers/waqfeya_handler.py
  tests/extensions/booksearch/conftest.py
  tests/extensions/booksearch/handlers/test_shamela_handler.py
  tests/extensions/booksearch/handlers/test_waqfeya_handler.py
  tests/extensions/booksearch/test_booksite.py
  tests/extensions/booksearch/test_handlers.py
  tests/res/shamela_search_sample.html
  tests/res/shamela_search_sample2.html
  tests/res/waqfeya_search_sample.html
  tests/res/waqfeya_search_sample2.html
Labels: bug, committed, enhancement

#21 Test PR
  .travis.yml
Labels: committed

#24 add command prefix synonyms
  .gitignore
  src/util.py
Labels: committed, enhancement

#25 Some mod commands
  src/extensions/mod/__init__.py
  src/extensions/mod/mod.py
Labels: committed, enhancement

#26 م
  src/extensions/meme/__init__.py
  src/extensions/meme/meme.py
  src/extensions/meme/psst.py
  tests/conftest.py
  tests/extensions/meme/test_psst.py
Labels: committed, enhancement

#27 Archive command now deletes command message
  src/extensions/archive/archive.py
Labels: committed, enhancement

#28 Storage wiring
  requirements.txt
  src/main.py
  src/storage.py
  src/util.py
  tests/test_storage.py
Labels: committed, enhancement
